version: '3'
services:
  dbINSTV1:
    image: postgres
    container_name: postgres_container_INSTV1
    restart: always
    ports:
      - "5434:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgresVF
      - POSTGRES_PASSWORD=postgresVF2024*
      #- DATABASE_HOST=127.0.0.1
    volumes:   # primero se debe crear un volumen respaldo_bd_afcorp
    #- /Users/homesis/Documents/Desarrollo/SistemaAFCorp/BasesDatos/BD_AFCV1/DatosAFC1:/var/lib/postgresql/data
    - /Users/homesis/Documents/Desarrollo/SistemaInstituto/BaseDatos/BD_INST1/DatosInstituto1:/var/lib/postgresql/data

  


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    container_name: web_INSTV1
    volumes: 
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - dbINSTV1


  